server:
  port: 8080

spring:
  application:
    name: mybatis-plus-dynamic-datasource-demo
  datasource:
    dynamic:
      primary: test # 设置默认的数据源或者数据源组,默认值为master
      strict: false   # 严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      datasource:
        test:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://dusp.mysql:33000/test?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&autoReconnect=true
          username: youlai
          password: 123456
        test2:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://dusp.mysql:33000/test2?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&autoReconnect=true
          username: youlai
          password: 123456

mybatis-plus:
  mapper-locations: classpath*:com/demo/dynamic/test/mapper/xml/*.xml,classpath*:com/demo/dynamic/test2/mapper/xml/*.xml
